### PR TITLE
New task063

### PR DESCRIPTION
**Pull request by egorgorchak**
Good evening!

Please consider the new Task to your repository. Task is about serialization, and it may be too easy, but in my opinion it would give  some basic skills. Plus, maybe in future somebody contribute a new ideas =)

### CODE REVIEW

**Comment by egorgorchak** [comment]
It's strange that checkstyle was failed because of missing JavaDoc in Test Class...

**Comment by aabarmin** [comment]
There is a check failure, could you please fix it first?

**Comment by aabarmin** [comment]
And one more thing, could you please change the number to `task062` please?

**Comment by egorgorchak** [comment]
All done

**Comment by aabarmin** [comment]
Thank you!

**Pull request merged**
