### PR TITLE
In test 009 and tasks 006-009 done

### PR DESCRIPTION
**Pull request by Ikiselev7**
I count with my hands, here would be 62 words
If you use Scanner or split(" ") some words include punctuation. This is the wrong way.
Task009Impl needs to take account punctuation, to match only words in result collection

### CODE REVIEW

**Comment by aabarmin** [comment]
Please, update your branch from master to get travis config

**Comment by aabarmin** [comment]
Amount of words updated in master branch, thank for your accuracy.

**Comment by Ikiselev7** [comment]
Thank you) 
what I need to do with Travis now?

**Comment by aabarmin** [comment]
Nothing, but it shows if all tests are passed and code have been written in accordance with google style guide. I'm trying to build a "real" CI for our pet tasks.

**Comment by Ikiselev7** [comment]
Ох, портянка-то какая)))

**Comment by Ikiselev7** [comment]
за все таски сразу)

**Comment by Ikiselev7** [comment]
I fixed all Travis remarks

**Pull request merged**
