### PR TITLE
Implements Task002

### PR DESCRIPTION
**Pull request by kimtox**
Implements Task002.

Created some methods for operations with Strings.

### CODE REVIEW

**Comment by aabarmin** [comment]
Hi,

It's expected your solutions will be stored in your own repository. Please take a look into the README.md for additional instructions.

Thanks,
Aleks

**Comment by kimtox** [comment]
> Hi,
> 
> It's expected your solutions will be stored in your own repository. Please take a look into the README.md for additional instructions.
> 
> Thanks,
> Aleks

> Got it
>
> Thanks

**Comment by aabarmin** [comment]
Hi, @kimtox, 

Should I close this PR or you'll do this? 

Thanks, 
Aleks

**Comment by kimtox** [comment]
My bad. 

This PR should be closed by me at that moment.

**Pull request closed without merging**
