### PR TITLE
Tasks up to 33. Project up to State Machine.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
com.epam.university.java.core.task031.Task031Test > testMultipleClients FAILED - 
because of the multithreading nature of the test.

**Comment by aabarmin** [comment]
There are a lot of style issues, could you please check them?

**Comment by ghost** [comment]
All of them are from unrealized part (book and state machine). 
Not correctly described commit in the title, my bad.

**Comment by aabarmin** [comment]
Well, ok

**Pull request merged**
