### PR TITLE
Tasks001-011 - completed

### PR DESCRIPTION
**Pull request by kmavropulo**
:dromedary_camel: :Task008-009 completed.

### CODE REVIEW

**Comment by aabarmin** [comment]
Tests failed. Could you fix them and push changes?

**Comment by konstantin-n-mavropulo** [comment]
Respected Alexander!
All tasks  and tests have been completed successfully.

But travis conclusion is: "80 tests completed, 1 failed
:test FAILED "

In IntelliJ all 001-009 tests passed successfully. Why?

**Comment by kmavropulo** [comment]
:bow_and_arrow: 

Respected Alexander!
All tasks and tests have been completed successfully.

**Comment by kmavropulo** [comment]
:bow_and_arrow: 

Respected Alexander!
Tasks 001-011 and tests - completed.

**Pull request merged**
