### PR TITLE
Task013

### PR DESCRIPTION
**Pull request by Hubbarus**

### CODE REVIEW

**Review by Hubbarus — COMMENTED** [review]
all good. trying to fight git

**Comment by aabarmin** [comment]
Hi, 

You should store your solutions in your own repository. 

Thanks.

**Comment by aabarmin** [comment]
Should I close this pull request? 

Thanks, 
Aleks

**Comment by Hubbarus** [comment]
Oh yes, sorry about not answering. 

С уважением,
Павел Пономарев
+7 981 8620217

**Comment by aabarmin** [comment]
Ok, closing the PR. 

Thanks and have a nice day
Aleks

**Pull request closed without merging**
