### PR TITLE
Tasks 014-023 - completed; style check warnings - fixed.

### PR DESCRIPTION
**Pull request by kmavropulo**
🏹 
Tasks 012-013 - completed. Validator class upgraded. CollectionFullException class created.

### CODE REVIEW

**Comment by aabarmin** [comment]
Please, fix style check warnings and I will merge your pull request. 
Have a nice day!)

**Comment by aabarmin** [comment]
Still have a style checker warnings.

**Comment by kmavropulo** [comment]
Respected Alexander!
Tasks 014-023 completed (except 016 and 021 - wich is under construction);
- code significantly upgraded, Logger class added; 
- all syntax mistakes fixed, except "incorrect indentation level" that is setted default by IDE.

**Comment by kmavropulo** [comment]
Style check warnings have been fixed! Pull request is ready to merging.

**Pull request merged**
