### PR TITLE
Task020

### PR DESCRIPTION
**Pull request by sluzhbin**

### CODE REVIEW

**Comment by aabarmin** [comment]
Hello, 

Your solutions should stay in your own repository, PRs are for new tasks or fixes only. 

Thanks, 
Aleks

**Comment by aabarmin** [comment]
Can I close this request, please?

**Comment by sluzhbin** [comment]
Yes, this pull request was wrong. Thank you!  21.10.2020, 10:24, "Aleksandr Barmin" <notifications@github.com>: Can I close this request, please?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aabarmin** [comment]
Thank you, closed

**Pull request closed without merging**
